### ISSUE TITLE
pardon me, I have some questions that I can't solve. Please help me

### ISSUE THREAD

**Issue by M-Kylie** [Xrondev/HKU-comp7404#1]
I'm a newbie. Where can the code run on, matlab, pycharm or other platform? And how can I run the code, I don't know the specific steps..

**Comment by Xrondev** [comment]
The implementation is based on Python, so yes you can run it with PyCharm, and you can check the result with the da_svm and woa_svm (.py)
**You may have to install the necessary libraries via `pip install [libraryname]`**
In addition, this is a rough course project for replicating the results, the paper we choose lacks some clarifications and details. 

This repo may be helpful for you if you want to learn metaheauristics algorithm [pyHeauristics ](https://github.com/Valdecy/pyMetaheuristic) we helped to fix an algorithm there. It will be easier for you if you just want to use the algorithms instead of implementing them by urself.

**Comment by M-Kylie** [comment]
Thank you for your reply! I can run it on my computer now. You're amazing!

But I have another problem. I'd appreciate it if you could do me a favor.

I can now see the results of the runs, but I don't know the meaning of the data that comes out of each .py file. Can you reply to my email, I will send you a picture to explain my problem. Excuse me, if you are inconvenient you can check it later.

my email:522832287@qq.com

**Comment by Xrondev** [comment]
I've replied mail to you, you can check your mailbox. 

Issue closed for no further comments.
